version: "3.9"

services:
  caddy:
    container_name: caddy
    image: iarekylew00t/caddy-cloudflare:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
      - "2019:2019"
    environment:
      - CF_API_TOKEN=${CF_API_TOKEN}
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/config.json:/etc/caddy/config.json
      - caddy_data:/data
      - caddy_config:/config
    command: caddy run --config /etc/caddy/config.json

volumes:
  caddy_data:
  caddy_config: